version: '3'

services:
  photos-service:
    build: ./
    command: sh -c 'npm install; npm start'
    volumes:
      - .:/src/app
    depends_on:
      - 'db'
    ports:
      - '5000:5000'

  db:
    image: mongo:latest
    ports:
      - 27017:27017